### PR TITLE
Reorganisation, Optimisation, Readme and Web Interface

### PR DESCRIPTION
**Pull request by PastaLaPate**
# Reorganisation
I reorganised all files folders etc to make it less line in main.py and more readable project
# Optimisation
I maked as comments print which make time to render
# Readme
I created the readme.md file
# Bar
I added alive_progress dependecy to add bars when loading flags

### CODE REVIEW

**Comment by iamEvanYT** [comment]
Thanks. This project is soooo not finished lol and I'm just using it to unlock FPS on my Roblox Client.

I'll check this later.

**Comment by PastaLaPate** [comment]
> Thanks. This project is soooo not finished lol and I'm just using it to unlock FPS on my Roblox Client.
> 
> 
> 
> I'll check this later. 

I think we should make a backend in python with flask and a front end with react and MUI which make it more simple and efficient than tkinter. I ´m working on the flask backend also tkinter canvas with a lot of entry is very hard to render for tkinter. I will make a PR when I finished the backend in a file called web.py and make the front in a directory called frontend

**Comment by PastaLaPate** [comment]
# Web interface
backend with flask + frontend with react and MUI 
Opening and closing roblox working, Changing Flags WIP

**Comment by iamEvanYT** [comment]
good job. one improvement is to add a single command to run the whole program

**Comment by iamEvanYT** [comment]
you might wanna make the FFlags scrolling frame bigger + different fflags use different types of input.

**Pull request merged**
